openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        examples:
          GET_DETAILS:
            value: 10
          UPDATE_DETAILS:
            value: 10
          DELETE_PRODUCT:
            value: 20
    get:
      summary: Fetch product details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Product'
              examples:
                GET_DETAILS:
                  value:
                    name: 'XYZ Phone'
                    type: 'gadget'
                    inventory: 10
                    id: 10
      operationId: get-product-id
    post:
      summary: Update product details
      operationId: post-products-id
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Update successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_DETAILS:
                  value:
                    name: 'XYZ Fone'
                    type: 'gadget'
                    inventory: 10
                    id: 10
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/Product'
            examples:
              UPDATE_DETAILS:
                value:
                  name: 'XYZ Fone'
                  type: 'gadget'
                  inventory: 10
                  id: 10
    delete:
      summary: Delete a product
      operationId: delete-products-id
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Deletion successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_PRODUCT:
                  value: ''
  /products:
    post:
      summary: Add new product
      operationId: post-products
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/ProductId'
              examples:
                ADD_PRODUCT:
                  value:
                    id: 10
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/ProductDetails'
            examples:
              ADD_PRODUCT:
                value:
                  name: 'XYZ Laptop'
                  type: 'gadget'
                  inventory: 10
    get:
      summary: Search for products
      operationId: get-products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './common.yaml#/components/schemas/Product'
              examples:
                SEARCH_1:
                  value:
                    - name: 'XYZ Fone'
                      type: 'gadget'
                      inventory: 10
                      id: 3
                SEARCH_2:
                  value:
                    - name: 'XYZ Fone'
                      type: 'gadget'
                      inventory: 10
                      id: 3
        '500':
          description: OK
          content:
            application/json:
              schema:
                type: string
      parameters:
        - schema:
            type: string
          in: query
          name: name
          examples:
            SEARCH_1:
              value:
            SEARCH_2:
              value: XYZ
        - schema:
            type: string
          in: query
          name: type
          examples:
            SEARCH_1:
              value: gadget
            SEARCH_2:
              value: gadget
  /orders:
    post:
      summary: Create an order
      operationId: post-orders
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/OrderId'
              examples:
                200_OK:
                  value:
                    id: 10
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/OrderDetails'
            examples:
              200_OK:
                value:
                  productid: 10
                  count: 1
                  status: pending
    get:
      summary: Search for orders
      operationId: get-orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './common.yaml#/components/schemas/Order'
              examples:
                200_OK:
                  value:
                    - productid: 10
                      count: 2
                      status: 'pending'
                      id: 10
      parameters:
        - schema:
            type: number
          in: query
          name: productid
          examples:
            200_OK:
              value: 10
        - schema:
            type: string
          in: query
          name: status
          examples:
            200_OK:
              value: fulfilled
      description: ''
  '/orders/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        examples:
          DETAILS:
            value: 10
    get:
      summary: Fetch order details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Order'
              examples:
                DETAILS:
                  value:
                    productid: 10
                    count: 2
                    status: 'pending'
                    id: 10
      operationId: get-orders-id
      parameters: []
    post:
      summary: Update order details
      operationId: post-orders-id
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_ORDER:
                  value:
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/Order'
            examples:
              UPDATE_ORDER:
                value:
                  productid: 10
                  id: 10
                  count: 1
                  status: pending
    delete:
      summary: Cancel an order
      operationId: delete-orders-id
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Cancel successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_ORDER:
                  value:
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authenticate
